//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageManagerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int ArchiveId { get; set; }
        public Nullable<int> PathId { get; set; }
        public string Directory { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public string FullPath { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Path Path { get; set; }
    }
}
