//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageManagerData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMDBModelContainer : DbContext
    {
        public IMDBModelContainer()
            : base("name=IMDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archive> Archives { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<MetaData> MetaDatas { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageSetting> PackageSettings { get; set; }
        public virtual DbSet<Path> Paths { get; set; }
        public virtual DbSet<Ranking> Rankings { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
        public virtual DbSet<TagType> TagTypes { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
