//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageManagerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int TagId { get; set; }
        public int PackageId { get; set; }
        public string Tag1 { get; set; }
        public int TypeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual TagType TagType { get; set; }
    }
}
